#!/usr/bin/env bash
#
# One-time setup for a fresh clone.
#
# The PROS build skeleton (Makefile, common.mk, firmware/, include/pros/) is
# generated by the PROS CLI rather than committed, so this script produces it
# and then installs LemLib. Files already in the repo are never overwritten:
# our src/ and include/robot/ take precedence over the generated defaults.
#
# Usage:  ./scripts/bootstrap.sh
set -euo pipefail

if ! command -v pros >/dev/null 2>&1; then
    echo "error: the PROS CLI is not on your PATH." >&2
    echo "Install it from https://pros.cs.purdue.edu/v5/getting-started/" >&2
    exit 1
fi

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
skeleton="$(mktemp -d)"
trap 'rm -rf "$skeleton"' EXIT

echo "==> Generating the PROS skeleton"
pros conduct new-project "$skeleton" --force

echo "==> Copying in only the files this repo does not already have"
cp -rn "$skeleton"/. "$repo_root"/

echo "==> Installing LemLib"
pros conduct apply LemLib

echo
echo "Done. Build with 'pros make' and upload with 'pros upload --slot 1'."
